name: Build with pkg

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      # Build pkg apps
      - name: pkg
        run: yarn && yarn build_docker_monitor && yarn build_uptime_monitor || exit 1

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: supervision-app
          path: |
            ./pkg/
