name: Build with pkg

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      # Build App with Neutralino Cli
      - name: Build app
        run: yarn && yarn build_pkg_linux || exit 1

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: supervision-app
          path: |
            ./pkg/
